export default {
  rss2json: 'https://api.rss2json.com/v1/api.json',
  CNN: 'http://rss.cnn.com/rss/edition.rss',
  foxSports: 'http://feeds.foxnews.com/foxnews/most-popular',
  BBC: 'http://feeds.bbci.co.uk/news/world/rss.xml',
  washingtonPost: 'http://feeds.washingtonpost.com/rss/world',
  independent: 'http://www.independent.co.uk/news/world/rss',
  techRadar: 'https://www.techradar.com/rss',
  FIFA: 'http://www.fifa.com/rss/index.xml',
  businessWire: 'https://feed.businesswire.com/rss/home/?rss=G1QFDERJXkJeFltUXw==',
  talkSport: 'https://talksport.com/rss/sports-news/all/feed',
  cNet: 'https://www.cnet.com/rss/news/',
  techCrunch: 'https://techcrunch.com/feed/rss',
  eOnline: 'http://syndication.eonline.com/syndication/feeds/rssfeeds/topstories.xml',
  eTOnline: 'http://feeds.feedburner.com/EtsBreakingNews',
  TMZ: 'http://www.tmz.com/rss.xml',
};
